[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "gcc"]

[phases.install]
cmds = [
    "cd frontend && npm install --frozen-lockfile",
    "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"